---
- hosts: all
  sudo: yes
  tasks:
    - name: install libselinux-python
      yum: name=libselinux-python state=latest
    - name: stop iptalbes
      service: name=iptables state=stopped enabled=no

- hosts: elasticsearch
  sudo: yes
  tasks:
    - name: Download and install the Public Signing Key for elasticsearch
      rpm_key: state=present key=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    - name: copy /etc/yum.repos.d/elasticsearch.repo
      copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo owner=root group=root
    - name: install jdk
      yum: name=java-1.7.0-openjdk state=latest
    - name: install elasticsearch
      yum: name=elasticsearch-1.3.4 state=latest
    - name: start elasticsearch
      service: name=elasticsearch state=started enabled=yes
    - name: copy /etc/elasticsearch/elasticsearch.yml
      template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
      notify:
      - reload elasticsearch
    - name: install plugin inquisitor
      command: /usr/share/elasticsearch/bin/plugin --install polyfractal/elasticsearch-inquisitor creates=/usr/share/elasticsearch/plugins/inquisitor
      notify:
      - reload elasticsearch
    - name: install plugin kuromoji for 1.3
      command: /usr/share/elasticsearch/bin/plugin --install elasticsearch/elasticsearch-analysis-kuromoji/2.3.0 creates=/usr/share/elasticsearch/plugins/analysis-kuromoji
      notify:
      - reload elasticsearch
    - name: install plugin elasticsearch-head
      command: /usr/share/elasticsearch/bin/plugin --install mobz/elasticsearch-head creates=/usr/share/elasticsearch/plugins/head
      notify:
      - reload elasticsearch
    - name: install plugin royrusso/elasticsearch-HQ
      command: /usr/share/elasticsearch/bin/plugin --install royrusso/elasticsearch-HQ creates=/usr/share/elasticsearch/plugins/HQ
      notify:
      - reload elasticsearch
    - name: install plugin OlegKunitsyn/elasticsearch-browser
      command: /usr/share/elasticsearch/bin/plugin --install OlegKunitsyn/elasticsearch-browser creates=/usr/share/elasticsearch/plugins/browser
      notify:
      - reload elasticsearch


  handlers:
    - name: reload elasticsearch
      action: service name=elasticsearch state=reloaded
